FROM debian:bullseye-slim

# 必要なパッケージのインストール
RUN apt-get update && apt-get install -y curl git unzip xz-utils libglu1-mesa

# Flutter SDKのインストール
RUN git clone https://github.com/flutter/flutter.git /flutter -b stable
ENV PATH="/flutter/bin:/flutter/bin/cache/dart-sdk/bin:${PATH}"

# Flutter doctorを実行してセットアップを確認
RUN flutter doctor

# 作業ディレクトリを設定
WORKDIR /app

# アプリケーションのコピー
COPY . /app

# Flutter依存関係の取得
RUN flutter pub get

# Flutter Webアプリをビルド
RUN flutter build web

   # nginxをインストールし、Flutterビルドをホスト
   FROM nginx:alpine
   COPY --from=0 /app/build/web /usr/share/nginx/html

   # nginxのデフォルト設定を削除し、カスタム設定を追加
   RUN rm /etc/nginx/conf.d/default.conf
   COPY nginx.conf /etc/nginx/conf.d

   # 80ポートを公開
   EXPOSE 80

   # nginxを起動
   CMD ["nginx", "-g", "daemon off;"]